services:
  toolbox:
    # TODO: It is recommended to pin to a specific image version instead of latest.
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    hostname: toolbox
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    env_file :
      - ./.env
    command:
      ["toolbox", "--tools-file", "/config/tools.yaml", "--address", "0.0.0.0"]
    depends_on:
      - mysql
      - mongodb
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: test
      MYSQL_USER: toolbox
      MYSQL_PASSWORD: toolbox_pass
volumes:
  mongo-data:
